version: 2.1

orbs:
  node: circleci/node@5.0.0
  php: circleci/php@1.1.0

jobs:
  php-lint:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - php/install-packages
      - run: composer lint

workflows:
  test-lint:
    jobs:
      - node/run:
          npm-run: lint:js
      - node/test:
          requires:
            - node/run
          matrix:
            parameters:
              version: [ '14.18', '15.0', '16.14', '17.4' ]
          run-command: test:js
      - php-lint
      - php/test:
          requires:
            - php-lint
          matrix:
            parameters:
              version: [ '7.3', '7.4', '8.0', '8.1' ]
